apiVersion: apps/v1
kind: Deployment
metadata:
  name: hueesw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hueesw
  template:
    metadata:
      labels:
        app: hueesw
    spec:
      containers:
      - image: okteto.dev/hueesw:latest
        name: hueesw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "269ba514-3e8f-49a8-ab5b-144d90450111"
        - name: Vless_Path
          value: "/shf5858"
        - name: Vmess_UUID
          value: "269ba514-3e8f-49a8-ab5b-144d90450111"
        - name: Vmess_Path
          value: "/cxg3535"
        - name: Share_Path
          value: "/v2link"
